/**
 * reportGenerator.js
 * Generates standalone, print-ready, visual HTML reports and shareable text summaries.
 */

/**
 * Generates a clean text/markdown summary suitable for sharing on messaging apps or email.
 */
export function generateTextSummary({
  expenses,
  totalSpent,
  formatCurrency,
  user,
  periodLabel = 'All Time',
  categoryStats = [],
}) {
  const dateStr = new Date().toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });

  let text = `📊 EXPENSSOR FINANCIAL REPORT\n`;
  text += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;
  text += `👤 Generated by: ${user?.name || 'User'}${user?.email ? ` (${user.email})` : ''}\n`;
  text += `📅 Date: ${dateStr}\n`;
  text += `⏱ Period: ${periodLabel}\n`;
  text += `💰 Total Spending: ${formatCurrency(totalSpent)}\n`;
  text += `🔢 Transactions: ${expenses.length}\n\n`;

  if (categoryStats.length > 0) {
    text += `📂 SPENDING BY CATEGORY:\n`;
    categoryStats.forEach((cat) => {
      text += `  • ${cat.name}: ${formatCurrency(cat.total)} (${cat.percentage.toFixed(1)}%)\n`;
    });
    text += `\n`;
  }

  if (expenses.length > 0) {
    text += `📝 RECENT TRANSACTIONS:\n`;
    expenses.slice(0, 10).forEach((exp) => {
      const d = new Date(exp.date).toLocaleDateString();
      text += `  • [${d}] ${exp.title} - ${formatCurrency(exp.amount)} (${exp.category})\n`;
    });
    if (expenses.length > 10) {
      text += `  ... and ${expenses.length - 10} more transactions.\n`;
    }
  }

  text += `\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;
  text += `Generated with Expenssor Expense Tracker`;

  return text;
}

/**
 * Generates a standalone, beautifully styled HTML document ready for printing, PDF saving, or sharing.
 */
export function generateHtmlReport({
  expenses,
  totalSpent,
  formatCurrency,
  user,
  periodLabel = 'All Time',
  categoryStats = [],
  highestExpense = null,
}) {
  const reportDate = new Date().toLocaleDateString(undefined, {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const categoriesRows = categoryStats
    .map(
      (cat) => `
    <tr>
      <td style="padding: 10px 12px; border-bottom: 1px solid #e2e8f0; font-weight: 600;">
        ${cat.icon || '📦'} ${cat.name}
      </td>
      <td style="padding: 10px 12px; border-bottom: 1px solid #e2e8f0; text-align: center;">
        ${cat.count}
      </td>
      <td style="padding: 10px 12px; border-bottom: 1px solid #e2e8f0; text-align: right; font-weight: 600;">
        ${formatCurrency(cat.total)}
      </td>
      <td style="padding: 10px 12px; border-bottom: 1px solid #e2e8f0; text-align: right;">
        ${cat.percentage.toFixed(1)}%
      </td>
    </tr>
  `
    )
    .join('');

  const transactionsRows = expenses
    .map(
      (exp) => `
    <tr>
      <td style="padding: 8px 12px; border-bottom: 1px solid #e2e8f0; color: #475569; font-size: 0.9rem;">
        ${new Date(exp.date).toLocaleDateString()}
      </td>
      <td style="padding: 8px 12px; border-bottom: 1px solid #e2e8f0; font-weight: 500; font-size: 0.9rem;">
        ${exp.title}
      </td>
      <td style="padding: 8px 12px; border-bottom: 1px solid #e2e8f0; font-size: 0.9rem;">
        <span style="background: #f1f5f9; padding: 2px 8px; border-radius: 4px; font-size: 0.8rem; font-weight: 500;">
          ${exp.category}
        </span>
      </td>
      <td style="padding: 8px 12px; border-bottom: 1px solid #e2e8f0; text-align: right; font-weight: 600; font-size: 0.9rem; color: #0f172a;">
        ${formatCurrency(exp.amount)}
      </td>
    </tr>
  `
    )
    .join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Expenssor Expense Report - ${periodLabel}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
      margin: 0;
      padding: 32px 24px;
      color: #0f172a;
      background: #f8fafc;
      line-height: 1.5;
    }
    .report-container {
      max-width: 900px;
      margin: 0 auto;
      background: #ffffff;
      padding: 40px;
      border-radius: 12px;
      box-shadow: 0 4px 20px rgba(0, 0, 0, 0.05);
      border: 1px solid #e2e8f0;
    }
    .no-print-bar {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 24px;
      padding: 12px 18px;
      background: #eff6ff;
      border: 1px solid #bfdbfe;
      border-radius: 8px;
    }
    .print-btn {
      background: #2563eb;
      color: #ffffff;
      border: none;
      padding: 8px 18px;
      border-radius: 6px;
      font-weight: 600;
      font-size: 0.9rem;
      cursor: pointer;
      display: inline-flex;
      align-items: center;
      gap: 6px;
    }
    .print-btn:hover {
      background: #1d4ed8;
    }
    .header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      border-bottom: 2px solid #e2e8f0;
      padding-bottom: 20px;
      margin-bottom: 24px;
    }
    .brand-title {
      font-size: 1.75rem;
      font-weight: 800;
      color: #1e293b;
      margin: 0;
    }
    .kpi-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
      gap: 16px;
      margin-bottom: 32px;
    }
    .kpi-card {
      background: #f8fafc;
      border: 1px solid #e2e8f0;
      border-radius: 8px;
      padding: 16px;
    }
    .kpi-label {
      font-size: 0.75rem;
      font-weight: 600;
      text-transform: uppercase;
      color: #64748b;
      margin-bottom: 6px;
    }
    .kpi-value {
      font-size: 1.4rem;
      font-weight: 800;
      color: #0f172a;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 12px;
      margin-bottom: 28px;
    }
    th {
      background: #f1f5f9;
      color: #475569;
      font-size: 0.8rem;
      font-weight: 700;
      text-transform: uppercase;
      padding: 10px 12px;
      border-bottom: 2px solid #cbd5e1;
    }
    .section-title {
      font-size: 1.15rem;
      font-weight: 700;
      color: #1e293b;
      margin: 28px 0 10px 0;
      border-bottom: 1px solid #e2e8f0;
      padding-bottom: 8px;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e2e8f0;
      display: flex;
      justify-content: space-between;
      color: #64748b;
      font-size: 0.8rem;
    }
    @media print {
      body {
        background: #ffffff;
        padding: 0;
      }
      .report-container {
        box-shadow: none;
        border: none;
        padding: 0;
      }
      .no-print-bar {
        display: none !important;
      }
    }
  </style>
</head>
<body>
  <div class="report-container">
    <div class="no-print-bar">
      <span style="font-size: 0.875rem; color: #1e40af; font-weight: 500;">
        💡 You can save this report as a PDF using your browser's Print dialog.
      </span>
      <button class="print-btn" onclick="window.print()">
        🖨️ Print / Save as PDF
      </button>
    </div>

    <div class="header">
      <div>
        <h1 class="brand-title">💎 Expenssor Financial Report</h1>
        <div style="color: #64748b; font-size: 0.9rem; margin-top: 4px;">
          Expense Ledger & Category Distribution
        </div>
      </div>
      <div style="text-align: right;">
        <div style="font-weight: 600; color: #0f172a;">${user?.name || 'Account Holder'}</div>
        <div style="font-size: 0.85rem; color: #64748b;">${user?.email || ''}</div>
        <div style="font-size: 0.8rem; color: #94a3b8; margin-top: 4px;">${reportDate}</div>
      </div>
    </div>

    <div class="kpi-grid">
      <div class="kpi-card">
        <div class="kpi-label">Total Period Spending</div>
        <div class="kpi-value">${formatCurrency(totalSpent)}</div>
      </div>
      <div class="kpi-card">
        <div class="kpi-label">Total Transactions</div>
        <div class="kpi-value">${expenses.length}</div>
      </div>
      <div class="kpi-card">
        <div class="kpi-label">Period Filter</div>
        <div class="kpi-value" style="font-size: 1.1rem; text-transform: uppercase;">${periodLabel}</div>
      </div>
      ${
        highestExpense && highestExpense.amount
          ? `
      <div class="kpi-card">
        <div class="kpi-label">Highest Expense</div>
        <div class="kpi-value" style="font-size: 1.15rem;">${formatCurrency(highestExpense.amount)}</div>
        <div style="font-size: 0.75rem; color: #64748b; margin-top: 2px;">${highestExpense.title || ''}</div>
      </div>
      `
          : ''
      }
    </div>

    ${
      categoryStats.length > 0
        ? `
    <h2 class="section-title">Spending Breakdown by Category</h2>
    <table>
      <thead>
        <tr>
          <th style="text-align: left;">Category</th>
          <th style="text-align: center;">Transactions</th>
          <th style="text-align: right;">Total Amount</th>
          <th style="text-align: right;">Share</th>
        </tr>
      </thead>
      <tbody>
        ${categoriesRows}
      </tbody>
    </table>
    `
        : ''
    }

    <h2 class="section-title">Detailed Transactions Ledger</h2>
    <table>
      <thead>
        <tr>
          <th style="text-align: left;">Date</th>
          <th style="text-align: left;">Description</th>
          <th style="text-align: left;">Category</th>
          <th style="text-align: right;">Amount</th>
        </tr>
      </thead>
      <tbody>
        ${transactionsRows || '<tr><td colspan="4" style="text-align: center; padding: 20px;">No transactions found.</td></tr>'}
      </tbody>
    </table>

    <div class="footer">
      <div>Expenssor &bull; Automated Expense Tracking System</div>
      <div>Page 1 &bull; Generated on ${new Date().toISOString().split('T')[0]}</div>
    </div>
  </div>
</body>
</html>`;
}

/**
 * Opens the generated HTML report in a new browser tab ready to view or print as PDF.
 */
export function openPrintableReport(reportHtml) {
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.open();
    printWindow.document.write(reportHtml);
    printWindow.document.close();
  } else {
    // If popups are blocked, create a temporary downloadable HTML file
    const blob = new Blob([reportHtml], { type: 'text/html;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `expense_report_${new Date().toISOString().split('T')[0]}.html`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }
}

/**
 * Downloads a standardized CSV export of the expenses.
 */
export function downloadCsvExport(expenses, currencyCode = 'USD') {
  if (!expenses || expenses.length === 0) return;
  const headers = ['Date', 'Description', 'Category', 'Amount', 'Currency'];
  const rows = expenses.map((exp) => [
    new Date(exp.date).toLocaleDateString(),
    `"${(exp.title || '').replace(/"/g, '""')}"`,
    `"${(exp.category || '').replace(/"/g, '""')}"`,
    exp.amount,
    currencyCode,
  ]);

  const csvContent =
    'data:text/csv;charset=utf-8,' +
    [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
  const encodedUri = encodeURI(csvContent);
  const link = document.createElement('a');
  link.setAttribute('href', encodedUri);
  link.setAttribute('download', `expenses_report_${new Date().toISOString().split('T')[0]}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

/**
 * Downloads a JSON backup/export of the expenses and summary metadata.
 */
export function downloadJsonExport(data, filename) {
  const jsonString = `data:text/json;charset=utf-8,${encodeURIComponent(JSON.stringify(data, null, 2))}`;
  const downloadAnchor = document.createElement('a');
  downloadAnchor.setAttribute('href', jsonString);
  downloadAnchor.setAttribute(
    'download',
    filename || `expenssor_data_export_${new Date().toISOString().split('T')[0]}.json`
  );
  document.body.appendChild(downloadAnchor);
  downloadAnchor.click();
  downloadAnchor.remove();
}
